import Foundation

/// Public access to library information
/// This file is automatically generated - do not edit manually
/// Run: ./update-version.sh to update
public enum LibraryInfo {
    /// The current version of the DesignSystem library
    public static let version = "0.38.0"
}
