#!/bin/bash

# Read version from VERSION file
VERSION=$(cat VERSION | tr -d '\n\r')

# Update LibraryInfo.swift
cat > Sources/DesignSystem/LibraryInfo.swift << EOF
import Foundation

/// Public access to library information
/// This file is automatically generated - do not edit manually
/// Run: ./update-version.sh to update
public enum LibraryInfo {
    /// The current version of the DesignSystem library
    public static let version = "$VERSION"
}
EOF

echo "✅ Updated LibraryInfo.swift with version $VERSION"